# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_VERSION: '8.0'
  PROJECT_PATH: ./Teste_Felipe_Santana_CapiGemini/Teste_Felipe_Santana_CapiGemini.csproj
  PROJECT_TESTE_PATH: ./Teste_Felipe_Santana_CapGemini_Test/Teste_Felipe_Santana_CapGemini_UnitTest.csproj
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_PATH}} 
    - name: Build
      run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore
    - name: Test
      run: dotnet test ${{env.PROJECT_TESTE_PATH}} --no-build --verbosity normal
